# Site settings
title: Domain7 FED Wiki
email: erik@domain7.com
description: "A place for Domain7 front end developers to checkout out great resources & coding standards."
baseurl: "/fed-wiki"
twitter_username: euunila
github_username:  eriku

# Build settings
highlighter: pygments
permalink: pretty
markdown: redcarpet

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-sass-converter