# Site settings
title: Domain7 Developer Wiki
tagline: A place for Domain7 developers to collect resources & coding standards.
author:
  email: erik@domain7.com
  twitter_username: euunila
  github_username:  eriku

# Build settings
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
permalink: pretty
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-sass-converter

sass:
    sass_dir: _sass
    style: :compressed

production_url: http://eriku.github.io/dev-wiki

baseurl: "/dev-wiki"
