# Site settings
title: F.E.D. Wiki
tagline: A place for Domain7 front end developers to checkout out great resources & coding standards.
author:
  email: erik@domain7.com
  twitter_username: euunila
  github_username:  eriku

# Build settings
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
permalink: pretty
markdown: redcarpet

gems:
  - jekyll-sitemap
  - jekyll-sass-converter

sass:
    sass_dir: _sass
    style: :compressed

production_url: http://eriku.github.io/dev-wiki

baseurl: "/dev-wiki"